<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/**
 * Created by Console.
 * User: Droideve Technology
 * Date: {date}
 * Time: {time}
 */

class Category extends MY_Controller {

    public function __construct(){
        parent::__construct();


        define('ADD_CATEGORY','add');
        define('EDIT_CATEGORY','edit');
        define('DELETE_CATEGORY','delete');


        /////// register module ///////
        $data = array(
            "version_code"  =>1,
            "version_name"  => "1.0.1 Beta",
            "order"     =>11
        );

        FModuleLoader::register($this,$data);

        TemplateManager::registerMenu(
            'offer',
            "category/menu",
            12
        );



    }

    //call it after loading all modules

    public function onLoaded()
    {
        parent::onLoaded(); // TODO: Change the autogenerated stub

        $this->registerModuleActions();

        //load model
        $this->load->model("category/category_model","mCategoryModel");

        $this->load->model("groupAccess_model","mGroupAccessModel");
        $this->load->helper("user/group_access");


    }

    private function registerModuleActions(){



        GroupAccess::registerActions("category",array(
            ADD_CATEGORY,
            EDIT_CATEGORY,
            DELETE_CATEGORY,
        ));

    }

	public function index()
	{

	}

}

/* End of file CategoryDB.php */