<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/**
 * Created by Console.
 * User: Droideve Technology
 * Date: {date}
 * Time: {time}
 */

class Gallery extends MY_Controller {

    public function __construct(){
        parent::__construct();

        define('KS_NBR_GALLERY_PER_STORE','nbr_gallery_per_store');
        define('MANAGE_GALLERY','manage_gallery');


        $data = array(
            "version_code"  =>1,
            "version_name"  => "1.0.1 Beta",
            "order"     =>9
        );

        FModuleLoader::register($this,$data);

        TemplateManager::registerMenu(
            'gallery',
            "gallery/menu",
            9
        );


        $this->load->model("gallery_model","mGalleryModel");

    }

    //call it after loading all modules
    public function onLoaded()
    {
        parent::onLoaded(); // TODO: Change the autogenerated stub

        $this->registerModuleActions();


        UserSettingSubscribe::set('gallery',array(
            'field_name' => KS_NBR_GALLERY_PER_STORE,
            'field_type' => UserSettingSubscribeTypes::INT,
            'field_default_value' => 30,
            'config_key' => 'NBR_GALLERY_PER_STORE',
            'field_label' => 'Number gallery allowed per Store',
            'field_comment' => '',
            '_display'      => 0
        ));


    }

    private function registerModuleActions(){


        GroupAccess::registerActions("gallery",array(
            MANAGE_GALLERY,
        ));

    }


}

/* End of file UploaderDB.php */