<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/**
 * Created by Console.
 * User: Droideve Technology
 * Date: {date}
 * Time: {time}
 */

class Messenger extends MY_Controller {

    public function __construct(){
        parent::__construct();


        define('USE_MESSENGER','send_and_receive');
        define('MANAGE_MESSAGES','manage_messages');


        $data = array(
            "version_code"  =>1,
            "version_name"  => "1.0.1 Beta",
            "order"     =>6
        );

        FModuleLoader::register($this,$data);

        TemplateManager::registerMenu(
            'messenger',
            "messenger/menu",
            6
        );

        //load model

        $this->load->model("messenger/messenger_model","mMessengerModel");
        $this->load->model("user/user_model","mUserModel");
        $this->load->model("user/user_browser","mUserBrowser");


    }

    public function onLoaded()
    {
        parent::onLoaded(); // TODO: Change the autogenerated stub

        $this->registerModuleActions();



    }

    private function registerModuleActions(){


        GroupAccess::registerActions("messenger",array(
            USE_MESSENGER,
            MANAGE_MESSAGES
        ));

    }



}

/* End of file MessengerDB.php */